# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8eb57c8653028a52b5d364fb30525cd09d5880b0d7b3c67dc889dd807b9cf74bfc0750989e5914413bdc16fa28fa7dd1ca6aeb63bb4a4e864b2e0fdad5854152

test:
  secret_key_base: 23e90a8da79d2e58921b282ed04230bff0778cc5f7de0face93e1350f81eef8c166a6674a1e802b0d12b3ecc3ab81c1c5a890a66a8ae84e0eb7396e6095964c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
